version: '3'

services:
  # PHP 8.1 FPM 容器
  php:
    build: .
    container_name: app_php
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - myapp_network
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  # Nginx 容器
  nginx:
    container_name: app_nginx
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - myapp_network

  # MySQL 8.0 容器
  db:
    container_name: app_db
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - myapp_network
    command: --default-authentication-plugin=mysql_native_password


volumes:
  db_data:

networks:
  myapp_network:
    driver: bridge
